name = "acrypto"
description = "Ada Cryptographic Objects"
version = "0.1.0-dev"
licenses = "Apache-2.0"

authors = ["Peter Chapin"]
maintainers = ["Peter Chapin <spicacality@kelseymountain.org>"]
maintainers-logins = ["pchapin"]
website = "https://github.com/pchapin/acrypto"

[build-switches]
"*".style_checks = "No"
