name = "acrypto_benchmarks"
description = "ACO benchmarks"
version = "0.1.0-dev"

authors = ["Peter Chapin"]
maintainers = ["Peter Chapin <spicacality@kelseymountain.org>"]
maintainers-logins = ["pchapin"]

executables = ["acrypto_benchmarks"]


[build-switches]
"*".style_checks = "No"

[[depends-on]]
acrypto = "*"

[[pins]]
acrypto = { path = ".." }
